### ISSUE TITLE
dependencies not found 

### ISSUE THREAD

**Issue by tetash1** [YangDai2003/Multi-Calculator-Android#1]
i want to contribute this project but dependencies are not found .if possable update full source code

**Comment by YangDai2003** [comment]
> i want to contribute this project but dependencies are not found .if possable update full source code

Hi, your contributions are welcome! But I've been busy with other things lately, I'll get the code sorted and uploaded in the next week, see you then!

**Comment by YangDai2003** [comment]
> i want to contribute this project but dependencies are not found .if possable update full source code

The latest code has been fully uploaded, so this issue will be closed.
