### ISSUE TITLE
Add app to alternative app store

### ISSUE THREAD

**Issue by Tarek-Hasan** [YangDai2003/Multi-Calculator-Android#2]
As an opensource app, you should add this app to opensource android app store [F-Droid](https://f-droid.org) or [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/info) App Repo.

**Comment by YangDai2003** [comment]
> 作为开源应用程序，您应该将此应用程序添加到开源 Android 应用程序商店[F-Droid](https://f-droid.org)或[IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/info) App Repo。

Publishing in multiple app markets takes a lot of my time and increases maintenance costs, which I won't consider at the moment.
