### ISSUE TITLE
Invalid input after doing special function (sin,cos, tan,...)

### ISSUE THREAD

**Issue by bimemto** [YangDai2003/Multi-Calculator-Android#5]
After I calculate a special function, press equal to show the result, then use this result to continue calculate another function, it always show Invalid Input
![2024-04-11 14 31 27](https://github.com/YangDai2003/Multi-Calculator-Android/assets/393472/1b0189b4-73e4-4636-8b29-996d41258a84)
![2024-04-11 14 31 24](https://github.com/YangDai2003/Multi-Calculator-Android/assets/393472/34d7a85c-e0c3-4cc8-b014-7a3c4bc665d7)

**Comment by YangDai2003** [comment]
> After I calculate a special function, press equal to show the result, then use this result to continue calculate another function, it always show Invalid Input ![2024-04-11 14 31 27](https://private-user-images.githubusercontent.com/393472/321539692-1b0189b4-73e4-4636-8b29-996d41258a84.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MzY0NTQsIm5iZiI6MTcxMjgzNjE1NCwicGF0aCI6Ii8zOTM0NzIvMzIxNTM5NjkyLTFiMDE4OWI0LTczZTQtNDYzNi04YjI5LTk5NmQ0MTI1OGE4NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxMTQ5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTlmMzFhZmYyZGZjNjNjODU0NzhhOTBkNjQ1NzIyYjgwMDc1YTllZWY3NmU3MGJkYWQ2MWIzMmM0MjQwYjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GaNz0hzW4Y8vb8EWre-V4BCYlxKEA8tJjq1BnV_z6es) ![2024-04-11 14 31 24](https://private-user-images.githubusercontent.com/393472/321539713-34d7a85c-e0c3-4cc8-b014-7a3c4bc665d7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MzY0NTQsIm5iZiI6MTcxMjgzNjE1NCwicGF0aCI6Ii8zOTM0NzIvMzIxNTM5NzEzLTM0ZDdhODVjLWUwYzMtNGNjOC1iMDE0LTdhM2M0YmM2NjVkNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxMTQ5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Yjc1ZWI1YmRhNzMxMWZhNjdmNTM1ZWZmYTI4MDc1MWZiMzRlZTUyMGY4M2UzNmU3ODI5MzIyOGJkOWZmMjk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UPJ3-oXdbD8l_L2p2V_-Dj1gKkwj6BJHY3Rqaee-qQE)

Thanks for your feedback, I've released v6.8 to fix the issue you described.
You can download the apk from github or wait for Google Play to push it.
